### ISSUE TITLE
404 link, but open as new tab is fine

### ISSUE THREAD

**Issue by HenryDev** [go-redis/redis-docs#7]
https://github.com/go-redis/redis-docs/blob/1ae2633f31e13df657523f3e5102295f5fae39aa/docs/guide/go-redis.md?plain=1#L127

In Firefox 109.0.1, clicking the tracing context link in [tracing context](https://redis.uptrace.dev/guide/go-redis.html#context) goes to https://redis.uptrace.dev/guide%2Fredis-performance-monitoring.html, but command click goes to https://redis.uptrace.dev/guide/go-redis-monitoring.html

**Comment by vmihailenco** [comment]
Should be fixed, thanks.
